name: dka-microservices-account

services:

  app:
    build:
      context: .
    profiles:
      - app
    container_name: <your-container-name>
    hostname: <your-container-hostname-name>
    working_dir: /home/app
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: 10
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 200M
    restart: always
    volumes:
      - type: volume
        source: account-app-data
        target: /home/app
    command: yarn run start:prod
    networks:
      - default

  mongo:
    image: mongo:latest
    profiles:
      - db
    container_name: <your-container-name>
    hostname: <your-container-hostname-name>
    environment:
      MONGO_INITDB_ROOT_USERNAME: <username>
      MONGO_INITDB_ROOT_PASSWORD: <password>
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 100M
    restart: always
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db
      - type: bind
        source: ./.config/mongo/mongod.conf
        target: /etc/mongod.conf
        read_only: true
    command: mongod --config /etc/mongod.conf
    networks:
      - default

volumes:
  account-app-data:
    driver: local
  mongodb-data:
    driver: local
  dka-ssl-data:
    driver: local

networks:
  default:
    driver: bridge